authorName: garen
experimentName: Task2.1 with assessor
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 10

trainingServicePlatform: local
searchSpacePath: search_space.json

useAnnotation: false

tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize

assessor:
  builtinAssessorName: Curvefitting
  classArgs:
    epoch_num: 10
    threshold: 0.9

trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 1
